export const countries = [
  { code: 'IE', region: 'Ireland', name: 'Ireland' },
  { code: 'XA', region: 'Ireland', name: 'Northern Ireland' },
  { code: 'GB', region: 'ROW', name: 'Great Britain' },
  { code: 'US', region: 'ROW', name: 'United States' },
  { code: 'AL', region: 'ROW', name: 'Albania' },
  { code: 'AS', region: 'ROW', name: 'American Samoa' },
  { code: 'AD', region: 'ROW', name: 'Andorra ' },
  { code: 'AO', region: 'ROW', name: 'Angola' },
  { code: 'AI', region: 'ROW', name: 'Anguilla' },
  { code: 'AG', region: 'ROW', name: 'Antigua And Barbuda' },
  { code: 'AR', region: 'ROW', name: 'Argentina' },
  { code: 'AW', region: 'ROW', name: 'Aruba' },
  { code: 'AU', region: 'ROW', name: 'Australia' },
  { code: 'AT', region: 'Europe', name: 'Austria' },
  { code: 'BS', region: 'ROW', name: 'Bahamas' },
  { code: 'BH', region: 'ROW', name: 'Bahrain' },
  { code: 'BD', region: 'ROW', name: 'Bangladesh' },
  { code: 'BB', region: 'ROW', name: 'Barbados' },
  { code: 'BE', region: 'Europe', name: 'Belgium' },
  { code: 'BZ', region: 'ROW', name: 'Belize' },
  { code: 'BJ', region: 'ROW', name: 'Benin' },
  { code: 'BM', region: 'ROW', name: 'Bermuda' },
  { code: 'BO', region: 'ROW', name: 'Bolivia' },
  { code: 'BA', region: 'ROW', name: 'Bosnia And Herzegovina' },
  { code: 'BW', region: 'ROW', name: 'Botswana' },
  { code: 'BR', region: 'ROW', name: 'Brazil' },
  { code: 'BG', region: 'Europe', name: 'Bulgaria' },
  { code: 'BF', region: 'ROW', name: 'Burkina Faso' },
  { code: 'BI', region: 'ROW', name: 'Burundi' },
  { code: 'KH', region: 'ROW', name: 'Cambodia' },
  { code: 'CM', region: 'ROW', name: 'Cameroon' },
  { code: 'CA', region: 'ROW', name: 'Canada' },
  { code: 'IC', region: 'ROW', name: 'Canary Islands ' },
  { code: 'CV', region: 'ROW', name: 'Cape Verde' },
  { code: 'KY', region: 'ROW', name: 'Cayman Islands' },
  { code: 'CF', region: 'ROW', name: 'Central African Republic' },
  { code: 'CL', region: 'ROW', name: 'Chile' },
  { code: 'CN', region: 'ROW', name: 'China' },
  { code: 'CX', region: 'ROW', name: 'Christmas Island' },
  { code: 'CC', region: 'ROW', name: 'Cocos (Keeling) Islands' },
  { code: 'CO', region: 'ROW', name: 'Colombia' },
  { code: 'KM', region: 'ROW', name: 'Comoros' },
  { code: 'CD', region: 'ROW', name: 'Congo Democratic Rep.' },
  { code: 'CK', region: 'ROW', name: 'Cook Islands' },
  { code: 'CR', region: 'ROW', name: 'Costa Rica' },
  { code: 'CI', region: 'ROW', name: 'Cote D Ivoire-Ivory Coast' },
  { code: 'HR', region: 'Europe', name: 'Croatia' },
  { code: 'CU', region: 'ROW', name: 'Cuba' },
  { code: 'CY', region: 'Europe', name: 'Cyprus' },
  { code: 'CZ', region: 'Europe', name: 'Czech Republic' },
  { code: 'DK', region: 'Europe', name: 'Denmark' },
  { code: 'DJ', region: 'ROW', name: 'Djibouti' },
  { code: 'DM', region: 'ROW', name: 'Dominica' },
  { code: 'DO', region: 'ROW', name: 'Dominican Republic' },
  { code: 'EC', region: 'ROW', name: 'Ecuador' },
  { code: 'EG', region: 'ROW', name: 'Egypt' },
  { code: 'SV', region: 'ROW', name: 'El Salvador' },
  { code: 'GQ', region: 'ROW', name: 'Equatorial Guinea' },
  { code: 'ER', region: 'ROW', name: 'Eritrea' },
  { code: 'EE', region: 'Europe', name: 'Estonia' },
  { code: 'ET', region: 'ROW', name: 'Ethiopia' },
  { code: 'FK', region: 'ROW', name: 'Falkland Islands-Malvinas' },
  { code: 'FO', region: 'ROW', name: 'Faroe Islands' },
  { code: 'FJ', region: 'ROW', name: 'Fiji' },
  { code: 'FI', region: 'Europe', name: 'Finland' },
  { code: 'FR', region: 'Europe', name: 'France' },
  { code: 'GF', region: 'ROW', name: 'French Guiana' },
  { code: 'PF', region: 'ROW', name: 'French Polynesia' },
  { code: 'TF', region: 'ROW', name: 'French Sth Territory' },
  { code: 'GA', region: 'ROW', name: 'Gabon' },
  { code: 'GM', region: 'ROW', name: 'Gambia' },
  { code: 'GE', region: 'ROW', name: 'Georgia' },
  { code: 'DE', region: 'Europe', name: 'Germany' },
  { code: 'GH', region: 'ROW', name: 'Ghana' },
  { code: 'GI', region: 'ROW', name: 'Gibraltar' },
  { code: 'GR', region: 'Europe', name: 'Greece' },
  { code: 'GL', region: 'ROW', name: 'Greenland' },
  { code: 'GD', region: 'ROW', name: 'Grenada' },
  { code: 'GP', region: 'ROW', name: 'Guadeloupe' },
  { code: 'GU', region: 'ROW', name: 'Guam' },
  { code: 'GT', region: 'ROW', name: 'Guatemala' },
  { code: 'GG', region: 'ROW', name: 'Guernsey' },
  { code: 'GN', region: 'ROW', name: 'Guinea' },
  { code: 'GW', region: 'ROW', name: 'Guinea-Bissau' },
  { code: 'GY', region: 'ROW', name: 'Guyana' },
  { code: 'HT', region: 'ROW', name: 'Haiti' },
  { code: 'HK', region: 'ROW', name: 'Hong Kong' },
  { code: 'HU', region: 'Europe', name: 'Hungary' },
  { code: 'IS', region: 'ROW', name: 'Iceland' },
  { code: 'IN', region: 'ROW', name: 'India' },
  { code: 'ID', region: 'ROW', name: 'Indonesia' },
  { code: 'IR', region: 'ROW', name: 'Iran' },
  { code: 'IQ', region: 'ROW', name: 'Iraq' },
  { code: 'IL', region: 'ROW', name: 'Israel' },
  { code: 'IT', region: 'Europe', name: 'Italy' },
  { code: 'JM', region: 'ROW', name: 'Jamaica' },
  { code: 'JP', region: 'ROW', name: 'Japan' },
  { code: 'JE', region: 'ROW', name: 'Jersey' },
  { code: 'JO', region: 'ROW', name: 'Jordan' },
  { code: 'KE', region: 'ROW', name: 'Kenya' },
  { code: 'KI', region: 'ROW', name: 'Kiribati' },
  { code: 'KR', region: 'ROW', name: 'Korea Republic (South)' },
  { code: 'KW', region: 'ROW', name: 'Kuwait' },
  { code: 'LA', region: 'ROW', name: 'Laos' },
  { code: 'LV', region: 'Europe', name: 'Latvia' },
  { code: 'LB', region: 'ROW', name: 'Lebanon' },
  { code: 'LS', region: 'ROW', name: 'Lesotho' },
  { code: 'LI', region: 'ROW', name: 'Liechtenstein' },
  { code: 'LT', region: 'Europe', name: 'Lithuania' },
  { code: 'LU', region: 'Europe', name: 'Luxembourg' },
  { code: 'MO', region: 'ROW', name: 'Macao' },
  { code: 'MK', region: 'ROW', name: 'Macedonia' },
  { code: 'MG', region: 'ROW', name: 'Madagascar' },
  { code: 'MW', region: 'ROW', name: 'Malawi' },
  { code: 'MY', region: 'ROW', name: 'Malaysia' },
  { code: 'MV', region: 'ROW', name: 'Maldives' },
  { code: 'ML', region: 'ROW', name: 'Mali' },
  { code: 'MT', region: 'Europe', name: 'Malta' },
  { code: 'MH', region: 'ROW', name: 'Marshall Islands' },
  { code: 'MQ', region: 'ROW', name: 'Martinique' },
  { code: 'MR', region: 'ROW', name: 'Mauritania' },
  { code: 'MU', region: 'ROW', name: 'Mauritius' },
  { code: 'MX', region: 'ROW', name: 'Mexico' },
  { code: 'FM', region: 'ROW', name: 'Micronesia Fed. States' },
  { code: 'MN', region: 'ROW', name: 'Mongolia' },
  { code: 'ME', region: 'ROW', name: 'Montenegro' },
  { code: 'MS', region: 'ROW', name: 'Montserrat' },
  { code: 'MA', region: 'ROW', name: 'Morocco' },
  { code: 'MZ', region: 'ROW', name: 'Mozambique' },
  { code: 'MM', region: 'ROW', name: 'Myanmar' },
  { code: 'NA', region: 'ROW', name: 'Namibia' },
  { code: 'NR', region: 'ROW', name: 'Nauru' },
  { code: 'NP', region: 'ROW', name: 'Nepal' },
  { code: 'NL', region: 'Europe', name: 'Netherlands' },
  { code: 'NC', region: 'ROW', name: 'New Caledonia' },
  { code: 'NZ', region: 'ROW', name: 'New Zealand' },
  { code: 'NE', region: 'ROW', name: 'Niger' },
  { code: 'NG', region: 'ROW', name: 'Nigeria' },
  { code: 'NU', region: 'ROW', name: 'Niue Island' },
  { code: 'NF', region: 'ROW', name: 'Norfolk Island' },
  { code: 'NO', region: 'ROW', name: 'Norway' },
  { code: 'OM', region: 'ROW', name: 'Oman' },
  { code: 'PK', region: 'ROW', name: 'Pakistan' },
  { code: 'PW', region: 'ROW', name: 'Palau Islands' },
  { code: 'PS', region: 'ROW', name: 'Palestinian Territory' },
  { code: 'PA', region: 'ROW', name: 'Panama' },
  { code: 'PG', region: 'ROW', name: 'Papua New Guinea' },
  { code: 'PY', region: 'ROW', name: 'Paraguay' },
  { code: 'PE', region: 'ROW', name: 'Peru' },
  { code: 'PH', region: 'ROW', name: 'Philippines' },
  { code: 'PN', region: 'ROW', name: 'Pitcairn Island' },
  { code: 'PL', region: 'Europe', name: 'Poland' },
  { code: 'PT', region: 'Europe', name: 'Portugal' },
  { code: 'PR', region: 'ROW', name: 'Puerto Rico' },
  { code: 'QA', region: 'ROW', name: 'Qatar' },
  { code: 'RE', region: 'ROW', name: 'Reunion' },
  { code: 'RO', region: 'Europe', name: 'Romania' },
  { code: 'RW', region: 'ROW', name: 'Rwanda' },
  { code: 'WS', region: 'ROW', name: 'Samoa' },
  { code: 'SM', region: 'ROW', name: 'San Marino' },
  { code: 'ST', region: 'ROW', name: 'Sao Tome And Principe' },
  { code: 'SA', region: 'ROW', name: 'Saudi Arabia' },
  { code: 'SN', region: 'ROW', name: 'Senegal' },
  { code: 'RS', region: 'ROW', name: 'Serbia' },
  { code: 'SC', region: 'ROW', name: 'Seychelles' },
  { code: 'SG', region: 'ROW', name: 'Singapore' },
  { code: 'SK', region: 'Europe', name: 'Slovakia' },
  { code: 'SI', region: 'Europe', name: 'Slovenia' },
  { code: 'ZA', region: 'ROW', name: 'South Africa' },
  { code: 'SS', region: 'ROW', name: 'South Sudan' },
  { code: 'ES', region: 'Europe', name: 'Spain' },
  { code: 'LK', region: 'ROW', name: 'Sri Lanka' },
  { code: 'SH', region: 'ROW', name: 'St. Helena' },
  { code: 'KN', region: 'ROW', name: 'St. Kitts And Nevis' },
  { code: 'LC', region: 'ROW', name: 'St. Lucia' },
  { code: 'PM', region: 'ROW', name: 'St. Pierre And Miquelon' },
  { code: 'VC', region: 'ROW', name: 'St. Vincent And Grenadines' },
  { code: 'SD', region: 'ROW', name: 'Sudan' },
  { code: 'SR', region: 'ROW', name: 'Suriname' },
  { code: 'SE', region: 'Europe', name: 'Sweden' },
  { code: 'CH', region: 'ROW', name: 'Switzerland' },
  { code: 'TW', region: 'ROW', name: 'Taiwan' },
  { code: 'TZ', region: 'ROW', name: 'Tanzania' },
  { code: 'TH', region: 'ROW', name: 'Thailand' },
  { code: 'TG', region: 'ROW', name: 'Togo' },
  { code: 'TK', region: 'ROW', name: 'Tokelau Islands' },
  { code: 'TO', region: 'ROW', name: 'Tonga' },
  { code: 'TT', region: 'ROW', name: 'Trinidad And Tobago' },
  { code: 'XT', region: 'ROW', name: 'Tristan Da Cunha' },
  { code: 'TN', region: 'ROW', name: 'Tunisia' },
  { code: 'TR', region: 'ROW', name: 'Turkey' },
  { code: 'TC', region: 'ROW', name: 'Turks And Caicos Islands' },
  { code: 'TV', region: 'ROW', name: 'Tuvalu' },
  { code: 'UG', region: 'ROW', name: 'Uganda' },
  { code: 'UA', region: 'ROW', name: 'Ukraine' },
  { code: 'AE', region: 'ROW', name: 'United Arab Emirates' },
  { code: 'UY', region: 'ROW', name: 'Uruguay' },
  { code: 'VU', region: 'ROW', name: 'Vanuatu ' },
  { code: 'VA', region: 'ROW', name: 'Vatican City State' },
  { code: 'VN', region: 'ROW', name: 'Vietnam' },
  { code: 'VG', region: 'ROW', name: 'Virgin Islands (British)' },
  { code: 'VI', region: 'ROW', name: 'Virgin Islands (USA)' },
  { code: 'WF', region: 'ROW', name: 'Wallis And Futuna Islands' },
  { code: 'ZM', region: 'ROW', name: 'Zambia' },
  { code: 'ZW', region: 'ROW', name: 'Zimbabwe' },
  { code: 'AF', region: 'ROW', name: 'Afghanistan' },
  { code: 'DZ', region: 'ROW', name: 'Algeria' },
  { code: 'AM', region: 'ROW', name: 'Armenia' },
  { code: 'AZ', region: 'ROW', name: 'Azerbaijan' },
  { code: 'BY', region: 'ROW', name: 'Belarus' },
  { code: 'BT', region: 'ROW', name: 'Bhutan' },
  { code: 'BN', region: 'ROW', name: 'Brunei Darussalam' },
  { code: 'SZ', region: 'ROW', name: 'Eswatini' },
  { code: 'HN', region: 'ROW', name: 'Honduras' },
  { code: 'KZ', region: 'ROW', name: 'Kazakhstan' },
  { code: 'KP', region: 'ROW', name: 'Korea Dem. Rep. (North)' },
  { code: 'KG', region: 'ROW', name: 'Kyrgyzstan' },
  { code: 'LY', region: 'ROW', name: 'Libya' },
  { code: 'MD', region: 'ROW', name: 'Moldova' },
  { code: 'AN', region: 'ROW', name: 'Netherlands Antilles' },
  { code: 'NI', region: 'ROW', name: 'Nicaragua' },
  { code: 'RU', region: 'ROW', name: 'Russian Federation' },
  { code: 'SB', region: 'ROW', name: 'Solomon Islands' },
  { code: 'SY', region: 'ROW', name: 'Syria' },
  { code: 'TJ', region: 'ROW', name: 'Tajikistan' },
  { code: 'TL', region: 'ROW', name: 'Timor-Leste' },
  { code: 'TM', region: 'ROW', name: 'Turkmenistan' },
  { code: 'UZ', region: 'ROW', name: 'Uzbekistan' },
  { code: 'VE', region: 'ROW', name: 'Venezuela' },
  { code: 'YE', region: 'ROW', name: 'Yemen' }
]
